site_name: Processes
site_url: https://oliverm91.github.io/processes/
repo_url: https://github.com/oliverm91/processes/
repo_name: oliverm91/processes

theme:
  name: material
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: cyan
      scheme: slate
      toggle:
        icon: material/brightness-4 
        name: Switch to light mode
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      accent: cyan
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
    - content.code.copy
    - navigation.top
    - navigation.tracking